[tool.poetry]
name = "loadfanet"
version = "0.1.0"
description = ""
authors = ["Vadim V"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
